version: '3'
services:
  pgsql:
    image: postgres:9.6.17
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=webfleet
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=webfleet
    volumes:
      - ./pgsql:/var/lib/postgresql/data
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_CREATE_TOPICS: "webfleet-domains:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  webfleet-domains:
    image: webfleet-domains:0.1.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - JDBC_DATABASE_URL=jdbc:postgresql://pgsql:5432/webfleet
      - DATABASE_USER=webfleet
      - DATABASE_PASS=password
      - AUTH_DOMAIN=https://ldsoftware.eu.auth0.com
      - AUTH_AUDIENCE=https://dev-env.webfleet.com
      - AUTH_ISSUER=https://ldsoftware.eu.auth0.com/
      - KAFKA_BROKERS=http://kafka:9092
      - DOMAINS_TOPIC=webfleet-domains
    depends_on:
      - pgsql
      - kafka